### ISSUE TITLE
offtop about CudaText

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_shell_extension#11]
Hello again. I want to ask for Pascal coding help. Cud will be better with 'tree helper for CSS' written in Pascal. Maybe you can write this helper?
Tree helper code is not hard to do, we have 3 treehelpers already, not much code!
https://github.com/Alexey-T/CudaText/blob/master/app/treehelpers_proc.pas
@dinkumoil

**Comment by dinkumoil** [comment]
Sorry, I can not do that.

1. I have only very limited knowledge of CSS.
2. I don't have enough spare time for working on any coding projects beyond my job. You might have noticed that I have completely stopped development on all my repos here on _GitHub_ and on _SourceForge_ as well.
