### ISSUE TITLE
User notes

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_shell_extension#4]
@dinkumoil User wrote me email:

Tested this new shell extension.
copy 2 files into folder: /cudatext:cudatext_shell64.dll, install_shell64.cmd.
run install_shell64.cmd and then select 17 files, right mouse opens context menu to open these 17 files, the "Open with CudaText" and its icon appears.
It is OK.
can open more than 15 files.
after finish this test, I copy "uninstall_shell64.cmd" into folder: /cudatext. then run it. The "Open with CudaText" and its icon disappears.

BTW, I noticed that the Notepad++ ( I used it before) can not do this. It can not open more than 15 files.
OS: Win10 X64 Ver 1803

**Comment by dinkumoil** [comment]
So, everything seems to be fine, right?

BTW: Under Windows 7 x64 and Windows 10 v1809 x64 Notepad++ can open more than 15 files using its context menu extension. The only reason I can imagine why that user failed to open more than 15 files is that he uses a self-made context menu entry using a simple `HKCR\*\shell\Notepad++\command` registry key.

**Comment by Alexey-T** [comment]
Yes, it’s ok, I plan to put this to distr. I need to put both Dll to x32 zip and only x64 Dll to x64 zip?

**Comment by dinkumoil** [comment]
> I need to put both Dll to x32 zip and only x64 Dll to x64 zip?

Yes, that's right. The version of the DLL a user needs depends on the bitness of the OS (i.e. 32 bit or 64 bit Explorer).
